BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text NOT NULL,
  google_subject text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'member',
  status text NOT NULL DEFAULT 'active',
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token_hash text PRIMARY KEY,
  user_id text NOT NULL,
  csrf_token text NOT NULL,
  expires_at text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS oauth_states (
  state_hash text PRIMARY KEY,
  code_verifier text NOT NULL,
  nonce text NOT NULL,
  next_path text NOT NULL DEFAULT '/',
  expires_at text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_oauth_states_expires ON oauth_states(expires_at);

CREATE TABLE IF NOT EXISTS resources (
  id text PRIMARY KEY,
  kind text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  url text,
  storage_key text,
  original_name text,
  mime_type text,
  size_bytes bigint,
  owner_id text NOT NULL,
  parent_id text,
  access_level text NOT NULL DEFAULT 'private',
  revision integer NOT NULL DEFAULT 1,
  trashed_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_resources_parent ON resources(parent_id);
CREATE INDEX IF NOT EXISTS idx_resources_owner ON resources(owner_id);
CREATE INDEX IF NOT EXISTS idx_resources_trash ON resources(trashed_at);

CREATE TABLE IF NOT EXISTS resource_members (
  resource_id text NOT NULL,
  user_id text NOT NULL,
  role text NOT NULL,
  PRIMARY KEY(resource_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_resource_members_user ON resource_members(user_id);

CREATE TABLE IF NOT EXISTS share_links (
  resource_id text PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  role text NOT NULL,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS resource_versions (
  resource_id text NOT NULL,
  revision integer NOT NULL,
  kind text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  url text,
  storage_key text,
  original_name text,
  mime_type text,
  size_bytes bigint,
  parent_id text,
  event text NOT NULL,
  actor_id text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY(resource_id, revision)
);
CREATE INDEX IF NOT EXISTS idx_resource_versions_created ON resource_versions(resource_id, created_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id text,
  action text NOT NULL,
  target_id text,
  details text NOT NULL DEFAULT '{}',
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at);

CREATE TABLE IF NOT EXISTS password_credentials (
  user_id text PRIMARY KEY,
  password_hash text NOT NULL,
  verified_at text NOT NULL,
  changed_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  token_hash text PRIMARY KEY,
  email text NOT NULL,
  purpose text NOT NULL,
  expires_at text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_email ON auth_tokens(email);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires ON auth_tokens(expires_at);

CREATE TABLE IF NOT EXISTS auth_rate_limits (
  key text PRIMARY KEY,
  hits integer NOT NULL,
  expires_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_rate_expires ON auth_rate_limits(expires_at);

COMMIT;
